auth_request /auth;
error_page 401 = @error401;

location @error401 {
    return 302 https://tinyauth.example.com/login?redirect_url=$scheme://$host$request_uri;
}

location = /auth {
    internal;
    proxy_pass              http://tinyauth:3000/api/auth;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length    "";
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_set_header        X-Original-URL    $scheme://$host$request_uri;
}
