server {
    include snippets/ssl-wildcard.conf;
    server_name ${APP_HOST};

    include snippets/proxy-headers.conf;
    include snippets/websocket.conf;
    ${CUSTOM_NGINX_INCLUDE}

    location / {
        proxy_pass http://${APP_UPSTREAM};
    }
}
